-- Which team run paid for this run, in the shape `runs.job_id` already established.
--
-- Numbered 0081, having been cut as 0072 and renumbered once to 0073 on the way. Master landed
-- `0072_job_notes.sql` (`02787ff`) and then `0073_vcs_escalated.sql` while this branch was being
-- built — the fourth and fifth times this repository has had two files with different names
-- claiming the same version, and, as `0065_council.sql` records at length, both times git reported
-- nothing: two such files merge clean, and only `sqlx::migrate!` finds them, at the daemon's next
-- start. Master now also has a test for it (`storage.rs::no_two_migrations_claim_the_same_version`),
-- which turns that start-up panic into a red gate. The rule held again, unchanged: the BRANCH gives
-- way, master's lineage stands.
--
-- **The jump past 0074-0080 is deliberate, and this branch's four files move together.** Master's
-- numbers stop at 0079 (`0079_browser.sql`) and the hole at 0074-0078 is not free space:
-- `feat/pilar-de-browser` stepped over it on its way in, leaving the block to `feat/assuntos`, which
-- has had those five and 0080 written for weeks. Filling it would make three of that branch's files
-- move so that none of these four had to — and these four were moving regardless. Starting above
-- everything master holds has a second property the hole cannot: a database that has already run
-- master's migrations never sees one of these arrive out of order.
--
-- The teams design said no existing table needed changing, and for four of the five columns it was
-- right. This is the fifth. `team_runs.director_run_id` names the director node IN FLIGHT and is
-- overwritten by the next one, so the plan node, the replan nodes and the delivery node of a
-- finished run are reachable from nothing — and `teams.budget_usd` is a per-run ceiling that would
-- therefore be computed from the specialists alone. A spend ceiling that undercounts is wrong in
-- the expensive direction.
--
-- `job_id` is the precedent and the reason this is a column rather than a join table:
-- `budget::job_rows` filters `WHERE job_id = ?` and deliberately does not filter by mode, because
-- every run carrying the id was started by the thing that owns it. The same is true here.
ALTER TABLE runs ADD COLUMN team_run_id TEXT REFERENCES team_runs(id);

CREATE INDEX idx_runs_team_run_id ON runs(team_run_id) WHERE team_run_id IS NOT NULL;
